### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cristiklein** [ibrokethecloud/kube-bench-metrics#1]
Hello,

We would like to integrate your module in [Compliant Kubernetes](https://compliantkubernetes.io).
Can you tell us what is the license for this repository?

Thanks!

**Comment by ibrokethecloud** [comment]
Added one @cristiklein. Hope that helps.

**Comment by cristiklein** [comment]
Apache 2.0 is perfect, thanks! @viktor-f, PTAL.
