### ISSUE TITLE
Future updates and maintainance

### ISSUE THREAD

**Issue by viktor-f** [ibrokethecloud/kube-bench-metrics#2]
Hi,

I have recently tested this wrapper and noticed that it used a rather old version of kube-bench. I managed to update it to the latest release and got it to run. I also updated the grafana dashboard a bit.

Would you be interested in accepting those updates and are you interested in continuing to maintain this project?
So far I just have the changes locally, but let me know if you want to see them.

**Comment by viktor-f** [comment]
@ibrokethecloud any thoughts on this?

**Comment by ibrokethecloud** [comment]
Hi @viktor-f please send through the changes and I will merge them.

I would be happy to keep this alive, i just wasnt sure after i wrote it if there was any interest for it.

**Comment by viktor-f** [comment]
Excellent, a PR is up now https://github.com/ibrokethecloud/kube-bench-metrics/pull/3
